# Generated by Django 4.2.20 on 2025-04-27 20:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Page description for SEO", max_length=255
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 5),
                            ("features", 12),
                            ("testimonials", 19),
                            ("content", 23),
                            ("cta", 29),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Title for the hero section",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Subtitle for the hero section",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Call to action button text",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Call to action button link",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Background image for the hero section",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("subtitle", 1),
                                        ("cta_text", 2),
                                        ("cta_link", 3),
                                        ("background_image", 4),
                                    ]
                                ],
                                {},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Section title", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Font Awesome icon class",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Feature title", "required": True},
                            ),
                            9: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Feature description", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 7), ("title", 8), ("description", 9)]],
                                {},
                            ),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("features", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Testimonial quote", "required": True},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Author name", "required": True},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Author role or company",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Author image", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("quote", 13),
                                        ("author", 14),
                                        ("role", 15),
                                        ("image", 16),
                                    ]
                                ],
                                {},
                            ),
                            18: ("wagtail.blocks.ListBlock", (17,), {}),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 6), ("testimonials", 18)]],
                                {},
                            ),
                            20: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Section content", "required": True},
                            ),
                            21: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Section image", "required": False},
                            ),
                            22: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("left", "Left"), ("right", "Right")],
                                    "help_text": "Position of the image",
                                },
                            ),
                            23: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 6),
                                        ("content", 20),
                                        ("image", 21),
                                        ("image_position", 22),
                                    ]
                                ],
                                {},
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "CTA title", "required": True},
                            ),
                            25: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "CTA text", "required": False},
                            ),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Button text", "required": True},
                            ),
                            27: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Button link", "required": True},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Background color (hex code)",
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 24),
                                        ("text", 25),
                                        ("button_text", 26),
                                        ("button_link", 27),
                                        ("background_color", 28),
                                    ]
                                ],
                                {},
                            ),
                        },
                        null=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Open Graph image (1200x630px recommended)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Landing Page",
                "verbose_name_plural": "Landing Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Analytics tracking ID (e.g., UA-XXXXXXXX-X)",
                        max_length=50,
                    ),
                ),
                (
                    "google_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Google Search Console verification code",
                        max_length=255,
                    ),
                ),
                (
                    "bing_site_verification",
                    models.CharField(
                        blank=True,
                        help_text="Bing Webmaster Tools verification code",
                        max_length=255,
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True, help_text="Default site description for SEO"
                    ),
                ),
                (
                    "twitter_site",
                    models.CharField(
                        blank=True,
                        help_text="Twitter site username (e.g., @site)",
                        max_length=50,
                    ),
                ),
                (
                    "facebook_app_id",
                    models.CharField(
                        blank=True, help_text="Facebook App ID", max_length=50
                    ),
                ),
                (
                    "default_og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default Open Graph image (1200x630px recommended)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LandingPageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="landing.landingpage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="landingpage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="landing.LandingPageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
